name: CI/CD Pipeline - Oracle Cloud Direct

on:
  push:
    branches: [ "Produccion" ]
  pull_request:
    branches: [ "Produccion" ]

jobs:
  # 1. ETAPA DE INTEGRACIÓN CONTINUA (CI)
  validate:
    name: Validar Proyecto
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Validar archivos mínimos
        run: |
          test -f README.md || (echo "ERROR: Falta README.md" && exit 1)

  # 2. ETAPA DE DESPLIEGUE CONTINUO (CD) - ORACLE CLOUD
  deploy-oracle:
    name: Despliegue en Oracle Cloud
    needs: validate
    # Solo se ejecuta en PUSH (no en Pull Requests)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Desplegar vía SSH en Oracle Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SSHKEY }}
          port: 22
          script: |
            cd /home/arturo/Backend-Arquitectura1
            git pull origin ${{ github.ref_name }}
            docker compose down
            docker compose up -d --build